kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: cert-manager-system
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager-system
    server: "https://kubernetes.default.svc"
  project: system-apps
  source:
    path: ""
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.7.1
    helm:
     values: |-
      installCRDs: true
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
